# 2.59%
dataset: Mnist
cost: CrossEntropy
layers:
- activation: Identity
  size: 784
- activation: Relu
  size: 700
- activation: Relu
  size: 400
- activation: Softmax
  size: 10
epochs: 2
learning_rate: 0.001
momentum: 0
weight_scale: 0.01
weight_decay: 0
evaluate_every: 5000
