# 6.42%
dataset: Mnist
cost: CrossEntropy
layers:
- activation: Identity
  size: 784
- activation: SparseField
  size: 625
- activation: SparseField
  size: 625
- activation: Softmax
  size: 10
epochs: 5
learning_rate: 0.01
momentum: 0.0
batch_size: 1
weight_scale: 0.001
weight_mean: 0.002
weight_decay: 0
evaluate_every: 5000
