language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
install:
  - pip install coveralls
script:
  - python setup.py test
  - python setup.py install
  - python setup.py build_sphinx
after_success:
  - coveralls
